apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: birthday-app
type: Opaque
stringData:
  POSTGRES_DB: employeedb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres123
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: birthday-app
data:
  POSTGRES_DB: employeedb
  POSTGRES_USER: postgres
